export const MAX_ACCOUNT_BALANCE = 100_000;
export const MIN_ACCOUNT_BALANCE = 0;
export const MIN_DEPOSIT_PER_TRANSACTION = 500;
export const MAX_DEPOSIT_PER_TRANSACTION = 50_000;
export const MIN_WITHDRAWAL_PER_TRANSACTION = 1000;
export const MAX_WITHDRAWAL_PER_TRANSACTION = 25_000;
export const MAX_DEPOSIT_COUNT_IN_A_DAY = 3;
export const MAX_WITHDRAWAL_COUNT_IN_A_DAY = 3;